### PR TITLE
Preparing release of 2.7.0

### PR DESCRIPTION
**Pull request by Lonzak**
Couldn't get the android stuff running since a lot of dependencies are missing. Except for that everything looks good...

### CODE REVIEW

**Comment by kenglxn** [comment]
nice! 
thanks @Lonzak  I will look at this in the morning.

**Comment by kenglxn** [comment]
Small update: 
I started looking at the state of things this morning, and regardless of this PR the roboelectric stuff is just broken. 
I spent some time trying to fix it, but it's a mess to be honest. Looks like they broke maven support a while back. 

Long story short. I should be able to merge your changes, I just have to get a passing build set up. Which also means I have to throw out robolectric.

**Comment by kenglxn** [comment]
> Yes I had the same impression with the roboelectric stuff. Strange thing. Thanks for the update...
> 
> PS: Maybe this helps? [robolectric/robolectric#3344](https://github.com/robolectric/robolectric/issues/3344)

Thanks. I spent quite some time looking into it, and decided to give up. If someone wants to reintroduce robolectric after the build is fixed without it that could be an option. I just dont have the time to fix it now.

**Comment by kenglxn** [comment]
- https://github.com/kenglxn/QRGen/pull/152

**Comment by kenglxn** [comment]
I will go ahead and merge this into a branch on my fork, and resolve the conflicts. It will be available as 3.0.0 since I had to bump to java 11

**Comment by Lonzak** [comment]
Ah really? So is the bytecode level also already java11? Damn we are still compiling with 8 ....

**Comment by kenglxn** [comment]
I resolved the conflicts. Now I will merge this into my fork and create the 3.0.0 release.

**Comment by kenglxn** [comment]
Thanks for the contrib @Lonzak 🎉

**Comment by Lonzak** [comment]
Thanks you as well!
Would it be possible to create a 2.7.0 compatible with Java8 (may be even 7 like it is now)? Unfortunately version 3.0.0 is now not usable for me and every effort would be in vain :-/

**Comment by kenglxn** [comment]
I'll give it a shot

**Comment by kenglxn** [comment]
Can you try this https://jitpack.io/#kenglxn/qrgen/2.7.0
hopefully works
```
        <dependency>
	    <groupId>com.github.kenglxn</groupId>
	    <artifactId>qrgen</artifactId>
	    <version>2.7.0</version>
	</dependency>
```

**Comment by Lonzak** [comment]
I am trying out right now...Will update when it is working...

**Pull request merged**
