### PR TITLE
Fixed that the URLs was always uppercase only.

### PR DESCRIPTION
**Pull request by laxika**
Fixing the URL QR code handling in the library.

### CODE REVIEW

**Comment by laxika** [comment]
@kenglxn Is there any chance that this fix will be released anytime soon?

**Comment by kenglxn** [comment]
It is now available as the -SNAPSHOT version through jitpack: https://jitpack.io/#kenglxn/QRGen/-SNAPSHOT

Will do a release as soon as I get time.

**Comment by kenglxn** [comment]
2.5.0 is released https://jitpack.io/#kenglxn/QRGen/2.5.0

**Comment by kenglxn** [comment]
https://github.com/kenglxn/QRGen/releases/tag/2.5.0

**Pull request merged**
